dev-version-ext            = "pre"
pre-release-commit-message = "Prepare to v{{version}} of {{crate_name}}"
pro-release-commit-message = "Start next development iteration v{{next_version}} of {{crate_name}}"
tag-message                = "Bump version to v{{version}}"
tag-prefix                 = ""
pre-release-replacements = [
    {file = "README.md", search = "nom-packrat = \"[a-z0-9\\.-]+\"", replace = "nom-packrat = \"{{version}}\""},
    {file = "nom-packrat/Cargo.toml", search = "nom-packrat-macros = \"[a-z0-9\\.-]+\"", replace = "nom-packrat-macros = \"{{version}}\""},
]
