[package]
name = "nom-packrat"
version = "0.1.0"
authors = ["dalance <dalance@gmail.com>"]
repository = "https://github.com/dalance/nom-packrat"
keywords = ["parser", "nom"]
categories = ["parsing"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "An extension of nom to apply Packrat Parsing"
edition = "2018"

[dependencies]
nom-packrat-macros = "0.1.0"

[dev-dependencies]
nom = "5.0.0"

[package.metadata.release]
disable-tag = true
