[package]
name = "nom-packrat"
version = "0.1.1"
authors = ["dalance <dalance@gmail.com>"]
repository = "https://github.com/dalance/nom-packrat"
keywords = ["parser", "nom"]
categories = ["parsing"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "An extension of nom to apply Packrat Parsing"
edition = "2018"

[package.metadata.release]
pre-release-replacements = [
    {file = "../README.md", search = "nom-packrat = \"[a-z0-9\\.-]+\"", replace = "nom-packrat = \"{{version}}\""},
    {file = "Cargo.toml", search = "nom-packrat-macros = \"[a-z0-9\\.-]+\"", replace = "nom-packrat-macros = \"{{version}}\""},
]

[dependencies]
nom-packrat-macros = "0.1.0"

[dev-dependencies]
nom = "5.0.0"
stats_alloc = "0.1.8"
